### ISSUE TITLE
OutOfBounds Exception when using orb

### ISSUE THREAD

**Issue by ereese99** [ZsoltMolnarrr/CombatSpells#10]
Spell Engine outofbounds (-1 instead of 36)
15.03 04:13:07 [Server] Server thread/ERROR Error executing task on Server
15.03 04:13:07 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 36
15.03 04:13:07 [Server] INFO at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?]
15.03 04:13:07 [Server] INFO at net.minecraft.class_2371.get(class_2371.java:47) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.class_1661.method_5438(class_1661.java:503) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.spell_engine.network.ServerNetwork.lambda$initializeHandlers$2(ServerNetwork.java:37) ~[spell_engine-fabric-0.9.15+1.19.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
15.03 04:13:07 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by ZsoltMolnarrr** [comment]
Please provide version information, full logs and a short description what exactly happened in game.
Did the game crash?

**Comment by ereese99** [comment]
Minecraft 1.19.2, Fabric 0.14.17, Mod Version 0.9.15

Does not crash, but I get error message in logs. That was the full message.

The item being used was from the Spellblades mod. (Fire Orb)

**Comment by ereese99** [comment]
Correction, it was the Arcane one

**Comment by ZsoltMolnarrr** [comment]
Will be resolved in next release, since slot sync will be removed entirely.
