### ISSUE TITLE
[Bug] Incompat with Mine Cell's weapon

### ISSUE THREAD

**Issue by pokesmells** [ZsoltMolnarrr/CombatSpells#15]
When using the katana ability, it registers as a spell weapon for some reason and also doesn't let me use the weapon.
https://gyazo.com/4e85f33f19de94de1237802302fe399e - with spell engine

https://gyazo.com/bee490bbafe7f08109018cae1e9065a9 - without spell engine

**Comment by pokesmells** [comment]
Using 1.19.2 on Fabric 0.14.19, on spell_engine-fabric-0.9.20+1.19

**Comment by ZsoltMolnarrr** [comment]
This is down to modpack creators to resolve, using fitting configuration.
Related from FAQ:

**How can I enable spell casting from spell books for specific items?**
You have multiple options:
A) If the weapon is a Sword (or some subclass of it) you can just leave `"add_spell_casting_to_swords": true` (in `config/spell_engine/server.json5`)
B) If the former has to be disabled, you can use regex: `"add_spell_casting_regex": "my_banana_sword|my_pineapple_axe"`  (in `config/spell_engine/server.json5`)
C) Specify the spell casting features of items using data files https://github.com/ZsoltMolnarrr/SpellEngine#-compatibility-for-third-party-content

**There is some modded weapon that has a right click action, now it conflicts with automatically assigned spell casting feature. How can I fix it?**
You have multiple options:
A) Disable automatically assigning spell casting capability, set `"add_spell_casting_to_swords": false` (in `config/spell_engine/server.json5`)
B) Add the specific item, or the all items from a mod to the related blacklist. `"blacklist_spell_casting_regex"`
The blacklist is a regex. It is matched against item ids. So for example to disable all weapons from `banana` and `apple` mods, use: `"banana:|apple:"`

Feel free to ask more, if this is not enough information.
