### ISSUE TITLE
Epic crash with Artifact

### ISSUE THREAD

**Issue by EnioSAF** [ZsoltMolnarrr/CombatSpells#16]
Hi,
I was playing on the CLUB SMP server with the Artifact mods and yours (alongside others).
I placed the whooping cushion from Artifact in the spell slot, and the moment I dropped the item, my game crashed.
I could not re-join the server anymore, my profile was corrupted and Minecraft was telling to ask the administrator because of the “culprit mod”.
We had to delete my server profile, so I can re-join the server.
Here is my log file : https://paste.atlauncher.com/view/92133716-b1f8-4f8b-9b65-9e100ad80be0

Thank you for your awesome mod anyway, I think it's a very niche bug and I love testing weird things, hope my post help :)
Have a nice day !

**Comment by ZsoltMolnarrr** [comment]
Fixed by 0.9.22.
Feel free to reopen the issue if the problem resurfaces.
Consider supporting the project via GitHub sponsors or Ko-Fi.🙏
