### ISSUE TITLE
Cast Spell

### ISSUE THREAD

**Issue by raziehEP** [ZsoltMolnarrr/CombatSpells#17]
While using other mods that have right click actions bound to right clicking with a weapon or tool, Spell Engine seems to override it and block their actions. 

Would it be possible to allow the user to choose which key cast spells?

**Comment by ZsoltMolnarrr** [comment]
Hello,

Reassigning spell casting from the use item hotkey is not possible.

FAQ on Discord:
**Weapons with a right click action, now conflict with automatically assigned spell casting feature. How can I fix it?**
You have multiple options:
A) Disable automatically assigning spell casting capability, set `"add_spell_casting_to_swords": false` (in `config/spell_engine/server.json5`)
B) Add the specific item, or the all items from a mod to the related blacklist. `"blacklist_spell_casting_regex"`
The blacklist is a regex. It is matched against item ids.
Example: to disable all weapons from `banana` and `apple` mods, use: `"banana:|apple:"`
Example: to disable a weapons with the following id `orange:orange_sword`, use: `"orange:orange_sword"`
C) Disable spell casting for a specific item using data files https://github.com/ZsoltMolnarrr/SpellEngine#%EF%B8%8F-disabling-spell-casting-capability-for-weapons
