### ISSUE TITLE
Can't interact with pets when spellengine is installed

### ISSUE THREAD

**Issue by Nichibokun** [ZsoltMolnarrr/CombatSpells#18]
It's like I never tamed them in the first place. They do follow me around but I cannot command them to sit or stand. Affects every tameable mob, which includes Horses. I can't put a saddle on my horses.

**Comment by ZsoltMolnarrr** [comment]
Using Spell Engine and RPG Series mods only does not cause this issue, with or without holding a spell casting weapon.
I recommend double checking what other mods you have installed.
