### ISSUE TITLE
Crash on Spell Engine 1.19.2 Fabric 0.14.21

### ISSUE THREAD

**Issue by pokesmells** [ZsoltMolnarrr/CombatSpells#19]
https://mclo.gs/eiOSXgF

Crash when using the spell table

**Comment by ZsoltMolnarrr** [comment]
Cannot reproduce the issue.
Seems like you have multiple packet manipulation mods installed.
Also, the server and client seem to have an inconsistent amount of spell books. This can be a result of some data manipulation.
Please provide specific details about how to reproduce this issue.

**Comment by Odaghast** [comment]
I received the same ( or at least very similar ) crash when shift + clicking a book out of the Spellbinding Table. I have yet to test this in a clean environment but I believe its due to vanillas quick stack moving leaving strange items stack values behind.

**Comment by ZsoltMolnarrr** [comment]
Can this issue be replicated consistently, or does it happen completely randomly?

**Comment by ZsoltMolnarrr** [comment]
Should be fixed by next update.
