### ISSUE TITLE
Cannot move spells to right side

### ISSUE THREAD

**Issue by ereese99** [ZsoltMolnarrr/CombatSpells#2]
Perhaps it's not possible yet, but I want to move the spells in the bottom left over to the bottom right

**Comment by ZsoltMolnarrr** [comment]
Have you tried dragging the spell hotbar?

**Comment by ZsoltMolnarrr** [comment]
In the current version you need to be holding a spell caster weapon.
The next version will come with a fix for this, and HUD config will always show a spell hotbar.
