### ISSUE TITLE
Spell creation info

### ISSUE THREAD

**Issue by swapmasterx** [ZsoltMolnarrr/CombatSpells#20]
No idea how to reach out other then hear so if this gets taken down I understand. Is there a more indepth tutorial resource for creating spells? I can put some of it together but the page doesn't go into much detail about big chunks of the spell syntax. Doesn't help I'm still new to reading syntax so if I could get some pointers or some hands on help setting up at least my first spell I'd be super grateful.

**Comment by ZsoltMolnarrr** [comment]
Hello!
I recommend discussing on Discord, it is linked to all project pages and readmes.
