### ISSUE TITLE
Horses aren't targeted by friendly healing spells

### ISSUE THREAD

**Issue by AngelTechnic** [ZsoltMolnarrr/CombatSpells#23]
Using the spells of the Priest from the Paladins and Priests mod here as an example.

Circle of Healing does not affect a tamed horse, even if you're not riding it. It'll affect tamed animals like cats and wolves, but a horse will not be affected.

Additionally, attempting to target it with a direct healing spell doesn't hurt the horse, but seems to redirect the healing towards the caster.

**Comment by ZsoltMolnarrr** [comment]
Horses don't extend the `TameableEntity` java class, part of vanilla code. This is a combination of multiple programming errors by Mojang.
If you want horses to be friendly by default you can now adjust the friend or foe ID list in the server config.
There is nothing more I would be able to do either.
