### ISSUE TITLE
Problem latest version

### ISSUE THREAD

**Issue by Roby1164** [ZsoltMolnarrr/CombatSpells#25]
with the latest versions of Spell Engine and Power, Fabric. 0.9.31+1.20.1 and 0.9.16+1.20.1, this error appeared in the log file, I attach screenshot:
![Screenshot_2](https://github.com/ZsoltMolnarrr/SpellEngine/assets/24955554/8593b4e7-537e-4dd5-aaf5-0da27a8df6c5)

**Comment by ZsoltMolnarrr** [comment]
Thank you for the report, fixing it with the next release of Spell Power Attributes.
