### ISSUE TITLE
0.10.0+1.20.1 causes crash on world load

### ISSUE THREAD

**Issue by JMackey1** [ZsoltMolnarrr/CombatSpells#27]
Been using this mod on the same world for a while now. Upgraded to 0.10.0 today and now my world won't load. Downgrading to 0.9.32 fixes the issue.

I've attached the crashlog.
[crash-2023-10-03_18.23.55-client.txt](https://github.com/ZsoltMolnarrr/SpellEngine/files/12797393/crash-2023-10-03_18.23.55-client.txt)

**Comment by ZsoltMolnarrr** [comment]
You need to update Simply Skills mod.
