### ISSUE TITLE
1.20.1 server ticking entity crash

### ISSUE THREAD

**Issue by FuturisticDruid** [ZsoltMolnarrr/CombatSpells#28]
Server crashed after player killed a magister from the Spellblades and such mod and then went near a portal from the mod.
crashlog says something about simply skills and spell engine
[crash-2023-10-15_02.00.49-server (1).txt](https://github.com/ZsoltMolnarrr/SpellEngine/files/12908562/crash-2023-10-15_02.00.49-server.1.txt)

**Comment by FuturisticDruid** [comment]
can't restart server. it crashes again with the same thing

**Comment by ZsoltMolnarrr** [comment]
You are using outdates versions of the mod.
Please do not submit issues about outdated versions.

Update your installations, and feel free reopen if this occurs with latest versions.
It is strongly recommended to use the desktop applications of [CurseForge](https://www.curseforge.com/download/app) or [Modrinth](https://modrinth.com/app), so you can actually see what needs updating, and can be done with a click.
