### ISSUE TITLE
Always show Spell Hotbar

### ISSUE THREAD

**Issue by 915Prophet** [ZsoltMolnarrr/CombatSpells#29]
Is there a way to enable a Persistent Spell hot bar for my equipped Spell book? Right now, I can only see the spell hot bar if I have an item able to cast spell book spells in my hand, even if the spell hot bar is supposed to be focused. Am I missing a config option?

**Comment by ZsoltMolnarrr** [comment]
Hello!

It is not possible, since Spell Hotbar content is also influenced by what item the player is holding.

**Comment by 915Prophet** [comment]
Would it be possible to add a rule to spell hotbar behavior where IF a spellbook is present in the Trinket slot, the hotbar is shown with the spellbook spells. Then if a player is holding an item that adds additional casting abilities, those are simply added on to the spell hotbar while the item is present in player’s hands

**Comment by ZsoltMolnarrr** [comment]
What game version are you using?
On the 1.20.1 version there is no more hotbar swapping.

**Comment by 915Prophet** [comment]
Oh I see. I am running the 1.19.2 version. By no more hot bar swapping, what do you mean by that?

**Comment by ZsoltMolnarrr** [comment]
1.19.2 versions are no longer being developed.
I recommend updating to 1.20.1, where Spell Engine offers keybindings to control individual spells.

**Comment by 915Prophet** [comment]
Do you plan to continue supporting the spell hot bar or is that effectively removed?
