### ISSUE TITLE
Bypass spell Hotbar

### ISSUE THREAD

**Issue by Mozork01** [ZsoltMolnarrr/CombatSpells#34]
Hey

Version 1.20.1
Fabric 0.14.24
Mod version 0.12.4

I can't use Bypass Spell Hotbar. I tried to change the key. The issue persists.

**Comment by Mozork01** [comment]
I have to use keyboard shortcuts, and personally, I don't like it.

**Comment by ZsoltMolnarrr** [comment]
Non actionable issue.

**Comment by Mozork01** [comment]
But what's the point of the bypass if it doesn't work? I wouldn't have understood how to use it?

**Comment by ZsoltMolnarrr** [comment]
It does work, I recommend chatting on discord instead. This is an issue tracker.
