### ISSUE TITLE
Casting animation while crouched has player's torso in wrong position

### ISSUE THREAD

**Issue by zlainsama** [ZsoltMolnarrr/CombatSpells#36]
Versions:
- player-animation-lib-fabric-1.0.2-rc1+1.20
- spell_engine-0.12.4+1.20.1
- paladins-1.0.4+1.20.1
- wizards-1.0.4+1.20.1

Note: The torso returns to correct position after few frames.
<details><summary>Screenshots</summary>

![2023-12-20_21 11 23](https://github.com/ZsoltMolnarrr/SpellEngine/assets/3251859/20859695-76c6-499c-865a-7ed67fa9d421)
![2023-12-20_21 12 14](https://github.com/ZsoltMolnarrr/SpellEngine/assets/3251859/2be1f13e-8d6f-4678-8820-96d846b60f87)

</details>

**Comment by ZsoltMolnarrr** [comment]
Fix in 1.21.1 versions by PlayerAnimator 2.0
