### ISSUE TITLE
[1.20.1] Crashes when dead 

### ISSUE THREAD

**Issue by Kaizuto** [ZsoltMolnarrr/CombatSpells#37]
https://mclo.gs/zNZ1OIT

**Comment by Kaizuto** [comment]
Ticking player is somehow related to spell engine?
[Screenshot](https://cdn.discordapp.com/attachments/607448149837086730/1190916359178162248/nWawfOT.png?ex=65a38a4a&is=6591154a&hm=93a0cc04b236c995a131d48980d1abd1760ada289f292fae17614c06c5ec13ba&)

**Comment by ZsoltMolnarrr** [comment]
Interesting issue, thanks, I'Ll take a look

**Comment by Kaizuto** [comment]
Found out that it has something to do with the Gravestone mod by Geometrically

**Comment by ZsoltMolnarrr** [comment]
I don't think this problem is up for Spell Engine to be fixed.
The thing is, it only may crash in case the trinket dataset of a player is so corrupted that Spell Engine cannot function.
