### ISSUE TITLE
Spell Binding Level Cost And Requirement Are Unconfigurable MC 1.20.1, Mod Version 0.12.4

### ISSUE THREAD

**Issue by AopoxlXil** [ZsoltMolnarrr/CombatSpells#39]
Setting ``"spell_book_binding_level_requirement"`` and ``"spell_book_binding_level_cost"`` to anything other than default values has no affect even after game restart.

**Comment by ZsoltMolnarrr** [comment]
There is no issue other than the name of the config being slightly misleading.
These define the cost of spell book creation, not spell assignment to spell books.
