### ISSUE TITLE
a subtle bug

### ISSUE THREAD

**Issue by Karashok-Leo** [ZsoltMolnarrr/CombatSpells#40]
https://github.com/ZsoltMolnarrr/SpellEngine/blob/a45c37cd4de4f1ec348a0c4a7aaa679c440856d6/src/main/java/net/spell_engine/internals/SpellHelper.java#L377

Should be setPitch...

**Comment by ZsoltMolnarrr** [comment]
Wow, thank you for the notice!
I haven't noticed this being an issue ingame. Have you?
