### ISSUE TITLE
Channeling/Target Spells cannot hit the Ender Dragon. 

### ISSUE THREAD

**Issue by Sazuzaki** [ZsoltMolnarrr/CombatSpells#42]
I know you mentioned somewhere in your discord that it's a hard solution, but I would be greatly appreciated if it would be a bigger priority if it isn't one already. Not being able to use magic on the final boss is quite a big downer.

**Comment by ZsoltMolnarrr** [comment]
This is a valid issue, however problematic due to the general performance overhead it brings.

**Comment by ZsoltMolnarrr** [comment]
Fixed in 0.13.0

Feel free to reopen if the problem still exists

**Comment by Sazuzaki** [comment]
Sounds good, I'll try it out later. Thanks for the hard work

**Comment by Sazuzaki** [comment]
It's definitely possible to hit the dragon with channeling spells now, but only under specific conditions it seems like. Arcane Beam only targets when the dragon seems to shift around while perched, and target-only spells such as Arcane Blast don't seem to hit at all still.

http://www.youtube.com/watch?v=Hjn_P09v8JI

Edit: Just realized the resolution is screwed. Sorry, just switched to a 1440p monitor. Here's another recording:

http://www.youtube.com/watch?v=zxSUkbKPp2k
