### ISSUE TITLE
Is it possible to have multiple item costs?

### ISSUE THREAD

**Issue by Pet-Slime** [ZsoltMolnarrr/CombatSpells#46]
I was looking into making a datapack that adds some additional spells to Wizards, but all I saw was a single item for the item ID in the costs instead of like an array. So is it possible to have multiple items be required for the spells or nay?

If Nay, would it be possible to get in the future?

**Comment by ZsoltMolnarrr** [comment]
Currently not possible, also it is rather costly on serverside to calculate such thing.
It might be added in the future.
