### ISSUE TITLE
empty nbt tag causes items not to stack

### ISSUE THREAD

**Issue by Alpdrucken** [ZsoltMolnarrr/CombatSpells#5]
I was using the latest version of Spell Engine and Spell Power Attribute for 1.19.2 and noticed that items the player gets (like from the creative inventory) often have an empty nbt tag (that can be seen with /data get entity @s SelectedItem), while items that are generated in chests dont have it, causing said items to not stack when in survival mode; for some reason they still stack in creative. Disabling those 2 mods solved the issue.

**Comment by Alpdrucken** [comment]
seems to happen on both 0.9.3 and 0.9.5

**Comment by ZsoltMolnarrr** [comment]
Hello!
Thanks a lot for the report and the all details.
The command you gave helped a lot too.
If you have a bit of spare time feel free to join Discord where I can give testable versions.

**Comment by ZsoltMolnarrr** [comment]
Fixed in 0.9.6.
Please reopen if the fix was unsuccessful, or the issue resurfaces.
