### ISSUE TITLE
Crash when entering world

### ISSUE THREAD

**Issue by muhammedesadcomert** [ZsoltMolnarrr/CombatSpells#50]
Minecraft: 1.20.1
Mod: 0.13.1

Crash logs: https://mclo.gs/7X6ezwn

**Comment by ZsoltMolnarrr** [comment]
This is a conflict between Spellblades and Spell Engine.
Spellblades needs an update, to support the new version of Spell Engine.

**Comment by muhammedesadcomert** [comment]
Hey @ZsoltMolnarrr thank you for your response. The compatibility issue was solved. But it has not been deployed yet to Modrinth, the up-to-date version is only available on Curseforge. This issue can be closed.
