### ISSUE TITLE
Game Crash on initializing or joining world

### ISSUE THREAD

**Issue by Alzrag** [ZsoltMolnarrr/CombatSpells#51]
log at https://pastebin.com/YdvaGXZC

mc veriosn: 1.20.1 fabric
mod version: 0.13.1

**Comment by ZsoltMolnarrr** [comment]
This is likely a conflict with another mod depending on the previous version of Spell Engine.
Maybe Simply Swords.

**Comment by Alzrag** [comment]
tried removing simply swords and i still getting thrown a simular message in the logs

https://pastebin.com/4A2L1P8A

**Comment by Alzrag** [comment]
went through and enabled and dissabled every mod to find the issue and it was invocations but it also had weird tie in stuff to wizards so I had to remove both launch the game, close it add wizards then relanch it for it to work

**Comment by ZsoltMolnarrr** [comment]
Several patches have been published.
Please update all of them.

**Comment by ZsoltMolnarrr** [comment]
Should be fixed in the latest patches. Feel free to reopen if not.
