### ISSUE TITLE
crash when loading saved world (1.20.1)

### ISSUE THREAD

**Issue by netcore10** [ZsoltMolnarrr/CombatSpells#53]
https://mclo.gs/qSKz34M
[crash-2024-03-31_22.20.39-client.txt](https://github.com/ZsoltMolnarrr/SpellEngine/files/14817654/crash-2024-03-31_22.20.39-client.txt)

**Comment by ZsoltMolnarrr** [comment]
I am unable to reproduce such crash.

Could you specify which is the absolute minimum set of mods to reproduce this? 

Or is there a specific inventory setup that causes this?

**Comment by ZsoltMolnarrr** [comment]
The crash is likely caused by another mod.
Make sure to update all of your mods. Closing the issue.
