### ISSUE TITLE
Disabling target filters does not allow PvP

### ISSUE THREAD

**Issue by PolyframeX** [ZsoltMolnarrr/CombatSpells#54]
When disabling target filters in the config, you still cannot target players and harm them with hostile spells.

Minecraft: 1.20.1
Mod Version: 0.13.3
Fabric: Latest

**Comment by ZsoltMolnarrr** [comment]
I don't understand sorry. What are target filters?

Here is what the FAQ says.

> **Why can I not hit other players or villagers with area spells (like Arcane Beam)?**
> The default configuration is PVE oriented, friendly towards villagers and other players.
> Put players into different teams to allow hurting each-other.
> Alternatively you can change this in Spell Engine server config (`config/spell-engine/server.json5`)
