### ISSUE TITLE
Crash on entering world

### ISSUE THREAD

**Issue by ChromaPIE** [ZsoltMolnarrr/CombatSpells#55]
1.20.1 Fabric
SE version 0.13.3

https://hastebin.com/share/beyarubome.yaml

**Comment by Nate4Fate** [comment]
Having the same issue, but on a dedicated server. Was working fine on SE version 0.13.0 I switched it to 0.13.3, but now none of the versions work. Tried on a new world, but same ticking crash.

**Comment by ZsoltMolnarrr** [comment]
Please provide the absolute minimum number of mods to reproduce.

Note: This is likely a crash due to some third party mod relying on internals of Spell Engine.

**Comment by Nate4Fate** [comment]
You're right, figured out the problem by disabling mods in bulk. "Spellblades and such" mod was causing the problem for my singleplayer world and server. Mod author pushed an update out today. Disregard my earlier concern.

**Comment by ChromaPIE** [comment]
Mine was caused by the other mod depending on SE from the same author. Had it updated then the issue's gone. Closing this issue.

**Comment by ZsoltMolnarrr** [comment]
@ChromaPIE thank you for the feedback. Could you tell me which mod exactly was causing the crash?

**Comment by ChromaPIE** [comment]
> @ChromaPIE thank you for the feedback. Could you tell me which mod exactly was causing the crash?

https://modrinth.com/mod/invocations
