### ISSUE TITLE
Cannot get into minecraft server with this mod... must load into singleplayer first

### ISSUE THREAD

**Issue by escobdan** [ZsoltMolnarrr/CombatSpells#58]
So I belive theres a bug calling these functions when joining my server:

java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null
     at net.spell_engine.compat.TrinketsCompat.getEquippedSpells(TrinketsCompat.java:58)
     at net.spell_engine.internals.SpellContainerHelper.getEquipped(SpellContainerHelper.java:51)
     at net.spell_engine.internals.SpellContainerHelper.getEquipped(SpellContainerHelper.java:39)
     at net.spell_engine.client.input.SpellHotbar.update(SpellHotbar.java:65)

If I however go into single player first and then go into the server, it works just fine. I do not have any spells on my server, so maybe that can help. Is there a way I can solve this?

**Comment by ZsoltMolnarrr** [comment]
This issue does not happen with Spell Engine and RPG Series mods only, but instead one of the third party content mods likely cause this (SimplySkills, Spell Blades).
Please make sure to update all of the mod installations to the very latest version, and ensure that server and clients have the exact same mod versions installed.

To handle mod updates easily, with a good overview, I typically recommend managing the modpack with the CurseForge desktop app (launcher), where it can also be exported for sharing.

Feel free to reopen if this is not resolved.
