### ISSUE TITLE
Critical error MC 1.19.2

### ISSUE THREAD

**Issue by Rox4me1** [ZsoltMolnarrr/CombatSpells#60]
MC 1.19.2 V0.9.27

Had multiple critical Mixin failures due to failure  of finding "Tail"

Had to downgrade to V.9.26 for it to work.

[latest.log](https://github.com/ZsoltMolnarrr/SpellEngine/files/15369919/latest.log)

**Comment by ZsoltMolnarrr** [comment]
I am unable to fix the problem.
I disabled SE 0.9.27.
Shoulder Surfing (if present) needs to be downgraded to 2.X.

**Comment by ZsoltMolnarrr** [comment]
Please note 1.19.X versions are no longer being developed.
