### ISSUE TITLE
"Saving entity NBT" crash

### ISSUE THREAD

**Issue by HaXrDEV** [ZsoltMolnarrr/CombatSpells#62]
Spell Engine 0.14.3+1.20.1
Spell Power Attribute 0.10.2+1.20.1
SimplySkills 1.4.1+1.20.1

https://gist.github.com/HaXrBOT/a2899ef70a126631b299e03535e369fd

This error crops up every now and again on a server i am running, but have yet to nail down the cause of the issue as it always happens when multiple people are online.

Related issue: https://github.com/Sweenus/SimplySkills/issues/89

**Comment by HaXrDEV** [comment]
Note that i have already tried removing mods like C2ME, Fast Async World Save, Smooth Chunk Save, VMP. Though the issue persists.

**Comment by HaXrDEV** [comment]
~~After a bit more testing, i found out that the issue was caused by DoesEntityTick. Removing that mod fixes the issue.~~

Scratch that, it is still happening.

**Comment by ZsoltMolnarrr** [comment]
The error is rather abstract.
I am unable to figure out why this is is happening. I have never seen anything like that.
I recommend trying other java JVMs, such as: Adoption Java 18, or 21.

**Comment by HaXrDEV** [comment]
I will try that and report back.

**Comment by HaXrDEV** [comment]
Unfortunately the issue still occurs after bumping the java version to 21. ~~I am not aware of which JVM distribution is being used specifically, as i am running it through a hosting provider.~~

https://gist.github.com/HaXrBOT/266096b17927a1ffd5fdc8912895afc8

Edit: Nevermind, from the log it looks to be Oracle HotSpot. I will try and ask if it is possible to change it to Adoptium.

**Comment by HaXrDEV** [comment]
Unfortunately it is not possible to change the JVM distribution with my hosting provider (BisectHosting).

Am i just out of luck then?

**Comment by TigerWalts** [comment]
Since Java 17 Java platform classes are now more strongly encapsulated. This means that Gson can no longer serialize java.util.Optional using reflection.

A Type Adapter is required to (de)serialize the class object.

- https://www.github.com/google/gson/issues/1979

If you are the owner of the class with the Optional field you can possibly annotate it with `@Expose` to allow access.

The alternatives are to register a generic Optional Type Adapter for Gson (Examples can be found via the above link) or use an alternative Json serializer that already has an adapter for the type.

I couldn't find an Optional field on any of the SpellProjectile fields being serialized or an fields on their children. maybe I didn't look hard enough.

**Comment by ZsoltMolnarrr** [comment]
This is a useful feedback.
Thank you very much.

**Comment by DistantDig** [comment]
[crash-2024-07-22_22.04.33-server.txt](https://github.com/user-attachments/files/16344049/crash-2024-07-22_22.04.33-server.txt)
I also have this issue on my server, and I can supply a crash report if it will be any help. We have a rather large mod list, but based on the report it seems to be this issue. The crash is extremely unreliable, but happens rather frequently for us. I hope this report helps and I wish you luck on this issue.

**Comment by ZsoltMolnarrr** [comment]
I attempted to fix this issue in the latest version (v0.15.8, requires Spell Power 0.11.1)
Please give feedback!

**Comment by ZsoltMolnarrr** [comment]
Should be fixed in Spell Engine 0.15.8.
Please reopen this issue, in case the problem occurs again with SE 0.15.8

**Comment by KevzCz** [comment]
Hello, excuse me :'Đ It's the same Saving entity NBT crash
Old Crash Report: https://mclo.gs/iLU0gBf
Latest Crash Report: https://mclo.gs/raUemAP
This crash is happening on two Fantasy MC modpack servers hosted by CDU. We're unsure what exactly everyone was doing before the crash happened.
Would appreciate any help! I'll try to answer any questions you have about the server specifics.
