### ISSUE TITLE
Channeling spells still have trouble hitting Ender Dragon.

### ISSUE THREAD

**Issue by Sazuzaki** [ZsoltMolnarrr/CombatSpells#63]
Hello, I made a similar report before this but am not sure how to re-open an issue.

To get to the point, spells that channel or require a target still have trouble hitting the dragon. It's not impossible anymore, but it needs a gamebreaking amount of precision and factors to get it to work properly. 

It seems to only target when the dragon shifts around while perching.

http://www.youtube.com/watch?v=zxSUkbKPp2k

**Comment by ZsoltMolnarrr** [comment]
The issue is present indeed.
I tried fixing it for hours, no success.
Vanilla Minecraft is doing some really shady logic with Ender Dragon.

I will attempt again later.
Fix PRs are welcome!

**Comment by ZsoltMolnarrr** [comment]
Fixed in 1.0.5+1.21.1
