### ISSUE TITLE
spell engine and killing entity with instant crash

### ISSUE THREAD

**Issue by KEJWII** [ZsoltMolnarrr/CombatSpells#64]
during final kill entity (vanilla zombie example)
the game freezes and crashes
I sending crashlog:
[crash-2024-06-19_15.02.34-server.txt](https://github.com/user-attachments/files/15902437/crash-2024-06-19_15.02.34-server.txt)

**Comment by ZsoltMolnarrr** [comment]
No such issue is is known.
The stacktrace top pints towards "Optional Enchants".

To make this issue actionable, please provide a method for reproducing the issue with Spell Engine + 1 RPG Series mod, and no other mod.

**Comment by KEJWII** [comment]
oh... ok
