### ISSUE TITLE
0.15.6 crash at world creation/loading

### ISSUE THREAD

**Issue by Shiroo2157** [ZsoltMolnarrr/CombatSpells#66]
[crash-2024-06-28_11.12.49-client.txt](https://github.com/user-attachments/files/16033283/crash-2024-06-28_11.12.49-client.txt)

Building a modpack
Made a duplicate, 
Updated spell engine today to 0.15.6.
Loaded up the pack to test functionality, deleted old world - crashed back to curse
Tried again, tried to use existing world - crashed while loading, back to curse

Spell engine is the only mod I updated which is why I'm posting here. 
Before the update / prior version 0.15.5, there was no issue. Now with paladins & priests having an update, spell engine also needs to update

**Comment by ZsoltMolnarrr** [comment]
Yeah, unfortunately I made a breaking API change, we need to ask Spell Blades to publish an update.

**Comment by ZsoltMolnarrr** [comment]
Please update your Spell Blades installation.
