### ISSUE TITLE
Add ability to customize the cost of spell tiers.

### ISSUE THREAD

**Issue by jaimarl** [ZsoltMolnarrr/CombatSpells#68]
It would be nice to be able to customize the cost of spell tiers and create your own tiers.

**Comment by ZsoltMolnarrr** [comment]
It is possible.
It is all data driven
![Screenshot 2024-07-23 at 22 31 19](https://github.com/user-attachments/assets/2287d550-2b11-4363-b6c0-add7b914bf49)
