### ISSUE TITLE
(NeoForge) spellbook slot missing 1.21.1

### ISSUE THREAD

**Issue by TerravoltPrime** [ZsoltMolnarrr/CombatSpells#72]
I cannot see the spellbook slot in my inventory, all RPG mods are up to date and I'm using accesories trinket layer as well

**Comment by muon-rw** [comment]
If you’re having issues with Accessories slots not showing up, you  should report it to them.

**Comment by ZsoltMolnarrr** [comment]
The mods you need to have to work with Accessories on Sinytra Connector, are:
- Trinkets
- Trinkets Compat Layer for Accessories
- Accessories

![image](https://github.com/user-attachments/assets/1a6bbb51-ff8a-4249-a631-bdb23a90d088)
