### ISSUE TITLE
Saving entity nbt crash

### ISSUE THREAD

**Issue by KevzCz** [ZsoltMolnarrr/CombatSpells#78]
Old Crash Report: https://mclo.gs/iLU0gBf
Latest Crash Report: https://mclo.gs/raUemAP
This crash is happening on two Fantasy MC modpack servers hosted by CDU. We're unsure what exactly everyone was doing before the crash happened.
Would appreciate any help! I'll try to answer any questions you have about the server specifics.

**Comment by ZsoltMolnarrr** [comment]
A safeguard against such crashes will be included in the next update of this mod.
I have no idea what causes this.
