### ISSUE TITLE
Incompatible versions.

### ISSUE THREAD

**Issue by JosePosadaSanchez** [ZsoltMolnarrr/CombatSpells#8]
Good morning. The reason for this dispute is to report an incompatibility and wait for a possible solution.
When trying to use the Wizard fabric 0.9.9+1.19 mod, you are asked for the spell_engine-fabric 0.9.9+1.19 library as a requirement. The problem is that I use minecraft version 1.19.1 and the spell engine file already mentioned, although it says that it is compatible for version 1.19.1 this file requires fabric api 0.70 or higher. There is no version 0.70 for version 1.19.1 of minecraft, since the latest version is the fabric api 0.58.5.
Is there a possibility to fix this error and make the spell engine file compatible with fabric api version 0.58.5? Thank you so much.

**Comment by ZsoltMolnarrr** [comment]
Spell Engine depends on new version of Fabric API, it crashes with 0.58 versions.
I removed the version support tags for 1.19.0 and 1.19.1 on CurseForge. Backports will not be implemented.
Sorry for the confusion.
