### ISSUE TITLE
[1.20.1] Spell Engine crashes to desktop (MC 1.20.1 - Spell Engine 0.15.10)

### ISSUE THREAD

**Issue by XavierBit** [ZsoltMolnarrr/CombatSpells#82]
Hi!
We are using the Fantasy MC Fabric 2.9.6b (https://www.curseforge.com/minecraft/modpacks/fantasy-minecraft-fabric) mod pack on our server which contains Spell Engine 0.15.10. After upgrading my abilities to 'Goliath' and 'Heavy weight' as well on the Berserker tree, the game crashes to desktop when I jump and land. It seems the automatically released projectiles are causing a render problem?

Please see my last crash log: https://mclo.gs/SJo9cLi

Thanks for any feedback!

**Comment by XavierBit** [comment]
Updating Indium, Sodium and Iris as well as your mod to 0.15.11 seems to make it a bit better but still crashes. 

See: https://mclo.gs/syi1faP

Edit: Seems it only crashes if I have an empty main hand?

**Comment by ZsoltMolnarrr** [comment]
Hello! I am unable to reproduce any such issue. This is most likely a problem with the content mod in question.
