### ISSUE TITLE
Mod requires a dependency that isn't on 1.21.1

### ISSUE THREAD

**Issue by vizthex123** [ZsoltMolnarrr/CombatSpells#83]
Seems like Player Animator hasn't been ported yet (or it hasn't been marked as being available for 1.21.1).

I manually downloaded the 1.21 version and it worked fine, so I think it just needs to be labelled as supporting this version.

**Comment by ZsoltMolnarrr** [comment]
Use the 1.21.0 version

**Comment by vizthex123** [comment]
can you mark it as supporting that version on the CurseForge page?

that's what i use to manage my modpacks, and not having it tagged properly makes it a bit annoying.
