### ISSUE TITLE
Can't "add spell casting capability for weapons" nor "disable spell casting capability for weapons"

### ISSUE THREAD

**Issue by gmikisilva** [ZsoltMolnarrr/CombatSpells#86]
When I follow the steps in:

https://github.com/ZsoltMolnarrr/SpellEngine/blob/1.20.1/README.md#%EF%B8%8F-adding-spell-casting-capability-for-weapons

Nothing seems actually take effect. I tried on both the data directory under the minecraft directory and under the data directory under my world save, am I doing something wrong? is there a different data directory that I missed?

Same thing happens with disabling spell capabilities in this link:

https://github.com/ZsoltMolnarrr/SpellEngine/blob/1.20.1/README.md#-disabling-spell-casting-capability-for-weapons

The items that I am trying to add are from a mod called Marium's Soulslike Weaponry, and the items that I tried to remove were the vanilla wooden and stone swords.

I am playing on Minecraft 1.20.1

Fabric version is 0.16.5

Mod version is 0.15.11

**Comment by ZsoltMolnarrr** [comment]
Items to be eligible for automatic compatibility must be some sort of Sword or Bow.

Also, changing assignments with data pack is possible, but very much prone to error.

The system definitely works. I recommend joining our Discord and showing the community your specific use case.

**Comment by gmikisilva** [comment]
> The system definitely works. I recommend joining our Discord and showing the community your specific use case.

The other items are indeed of type Sword (obviously the vanilla sword also is of this type, so there could still be some issue). The source code of the other mode has the inheritance as follows:
Sword --> ModdedSword --> ItemThatIWantToUse

Interestingly, other items in that same mod have a very similar structure, and they seem to work fine, is just with some specific items.

But regardless, I will try the discord because this seems like a very specific case, could you please provide me with the discord link? the only one I found said it was expired.
