### ISSUE TITLE
[1.20.1] Broken Quiver integration

### ISSUE THREAD

**Issue by yKvin** [ZsoltMolnarrr/CombatSpells#88]
I tried in creative mode, doing so will not cause a crash
This is the crash report
[crash-2024-12-02_22.00.02-client.txt](https://github.com/user-attachments/files/17979007/crash-2024-12-02_22.00.02-client.txt)
and latest log
[latest.log](https://github.com/user-attachments/files/17979039/latest.log)

**Comment by shardclay** [comment]
Have same error thet u have.
But in new world work perfectly. If delete Suplementary mod crash is disapeard in both worlds. 
Waiting for fix plsplsplspls

**Comment by ZsoltMolnarrr** [comment]
Seems like our integration with Suplementaries is broken, due to API changes on their behalf.
I will have to disable this integration.

**Comment by Dralaon** [comment]
@yKvin @shardclay 

This is working for me: https://github.com/Dralaon/SpellEngine---Removed-Quiver-Compat-1.20.1/releases/tag/0.15.12%2B1.20.1
Delete the 0.15.11 version before.

**Comment by ZsoltMolnarrr** [comment]
Thank you to @Dralaon, the PR was useful as I currently do not have a Java 17 build environment.

Released just now, feel free to reopen the issue if crashes with the new version occur.
