### ISSUE TITLE
[1.20.1] Supplementaries Quiver Crashing

### ISSUE THREAD

**Issue by BuilderDan** [ZsoltMolnarrr/CombatSpells#92]
[crash-2024-12-21_17.03.54-client.txt](https://github.com/user-attachments/files/18220452/crash-2024-12-21_17.03.54-client.txt)

It happens when you put the Archer book in the Spell Binding Table. Crashes client and appears to delete the contents of the table.

**Comment by ZsoltMolnarrr** [comment]
A fix has already been published.

https://curseforge.com/minecraft/mc-mods/spell-engine/files/6009091
